### PR TITLE
Support 2-interval Equilibrium Measures

### PR DESCRIPTION
**Pull request by dlfivefifty**
The test shows a known example, but we are still missing the log kernel constraint.

### CODE REVIEW

**Comment by dlfivefifty** [comment]
The good news: Equilibrium measures with two intervals now works! It's on the order of 32s so comparable to Mathematica's 10s. 

The bad news: I once got a random vector of `NaN`... this means there's some buried place where we are not setting entries to zeros...my best guess is it's in the generic (non-LAPACK) block banded QR...

**Comment by ioannisPApapadopoulos** [comment]
I am currently getting the following error when attempting the two-interval case in the tests. I imagine I am on the wrong branch of `BlockBandedMatrices` but I've switched to the current PRs with no effect. Do you have an idea what might be happening? 

```
ERROR: LoadError: MethodError: no method matching _apply_qr!(::ArrayLayouts.ColumnMajor, ::ArrayLayouts.DenseColumnMajor, ::ArrayLayouts.DenseColumnMajor, ::SubArray{ForwardDiff.Dual{ForwardDiff.Tag{EquilibriumMeasures.EquilibriumMeasureMoment, Float64}, Float64, 4}, 2, BlockBandedMatrices.BlockBandedMatrix{ForwardDiff.Dual{ForwardDiff.Tag{EquilibriumMeasures.EquilibriumMeasureMoment, Float64}, Float64, 4}}, Tuple{BlockArrays.BlockSlice{BlockArrays.BlockRange{1, Tuple{UnitRange{Int64}}}, BlockArrays.BlockedUnitRange{Vector{Int64}}}, BlockArrays.BlockSlice{BlockArrays.Block{1, Int64}, UnitRange{Int64}}}, false}, ::SubArray{ForwardDiff.Dual{ForwardDiff.Tag{EquilibriumMeasures.EquilibriumMeasureMoment, Float64}, Float64, 4}, 1, Vector{ForwardDiff.Dual{ForwardDiff.Tag{EquilibriumMeasures.EquilibriumMeasureMoment, Float64}, Float64, 4}}, Tuple{UnitRange{Int64}}, true}, ::SubArray{ForwardDiff.Dual{ForwardDiff.Tag{EquilibriumMeasures.EquilibriumMeasureMoment, Float64}, Float64, 4}, 1, BlockArrays.PseudoBlockVector{ForwardDiff.Dual{ForwardDiff.Tag{EquilibriumMeasures.EquilibriumMeasureMoment, Float64}, Float64, 4}, SubArray{ForwardDiff.Dual{ForwardDiff.Tag{EquilibriumMeasures.EquilibriumMeasureMoment, Float64}, Float64, 4}, 1, Vector{ForwardDiff.Dual{ForwardDiff.Tag{EquilibriumMeasures.EquilibriumMeasureMoment, Float64}, Float64, 4}}, Tuple{UnitRange{Int64}}, true}, Tuple{BlockArrays.BlockedUnitRange{Vector{Int64}}}}, Tuple{BlockArrays.BlockSlice{BlockArrays.BlockRange{1, Tuple{UnitRange{Int64}}}, BlockArrays.BlockedUnitRange{Vector{Int64}}}}, false})
Closest candidates are:
  _apply_qr!(::ArrayLayouts.AbstractColumnMajor, ::ArrayLayouts.AbstractStridedLayout, ::ArrayLayouts.AbstractStridedLayout, ::AbstractMatrix{T}, ::AbstractVector{T}, ::AbstractVecOrMat{T}) where T<:Union{Float32, Float64} at C:\Users\john.papad\.julia\dev\BlockBandedMatrices\src\blockskylineqr.jl:4
  _apply_qr!(::ArrayLayouts.AbstractColumnMajor, ::ArrayLayouts.AbstractStridedLayout, ::ArrayLayouts.AbstractStridedLayout, ::AbstractMatrix{T}, ::AbstractVector{T}, ::AbstractVecOrMat{T}) where T<:Union{ComplexF32, ComplexF64} at C:\Users\john.papad\.julia\dev\BlockBandedMatrices\src\blockskylineqr.jl:6
```

**Comment by dlfivefifty** [comment]
Ah, turns out I forgot to push some changes. 

https://github.com/JuliaMatrices/BlockBandedMatrices.jl/pull/120/

but you'll also need to be on

https://github.com/JuliaMatrices/MatrixFactorizations.jl/pull/29

I should probably come up with a better system for sharing the right branches... we could just have a "dev" branch in each of the relevant repositories but I think that has it's own problems when we want to merge into master...

**Comment by dlfivefifty** [comment]
OK I fixed the inconsistency bug (a simple issue with not properly truncating vectors). It should also only take around 15s, so pretty comparable to Mathematica (and with lots of room for improvement).

Now to get everything tagged....

**Comment by ioannisPApapadopoulos** [comment]
Thanks you @dlfivefifty, it's almost working for me now! It works completely if I remove the splatting from lines 90 & 92 in `src/EquilibriumMeasure.jl`. For the record, I needed the following branches:

LazyBandedMatrices -  https://github.com/JuliaMatrices/LazyBandedMatrices.jl#dl/blockbroadcastpadded
InfiniteLinearAlgebra  - https://github.com/JuliaMatrices/InfiniteLinearAlgebra.jl#dl/compact
ClassicalOrthogonalPolynomials - https://github.com/JuliaApproximation/ClassicalOrthogonalPolynomials.jl#dl/mappedweighted
BlockBandedMatrices - https://github.com/JuliaMatrices/BlockBandedMatrices.jl#dl/translayout
EquilibriumMeasures - https://github.com/JuliaApproximation/EquilibriumMeasures.jl#dl/twointerval

(MatrixFactorizations had been merged).

**Comment by dlfivefifty** [comment]
Ah yes I had broken the tests, I pushed your suggested fixes.

Note the `equilibriummeasure` routine doesn't yet work with 2 intervals. For now we can use the length of the initial guess to determine the number of supports. I may move the deflation stuff in to a separate routine.

(In Mathematica I had what I thought was a pretty good automated procedure: try 1 interval, and if the measure is negative, break into 2. Though your deflation stuff kind of shows a flaw that it might converge to something that is positive but not the minimiser. There is a condition that the energy will be less off the support if you aren't at the global minimiser so we could in theory check for this, but perhaps we don't really need to make things 100% automated right now since it's not really the point.)

**Comment by ioannisPApapadopoulos** [comment]
Great, thanks! Why do you say it's not working yet? For instance the following two-interval attempt gives me the endpoints `a` no problem:
```
using EquilibriumMeasures, StaticArrays

V = x -> (x-3)*(x-2)*(1+x)*(2+x)*(3+x)*(2x-1)/20
ic = SVector(-3.,-2.,2.,3.)
m, a = equilibriummeasure(V; a=ic, returnendpoint=true)
```

Although I have noticed that `plot(m)` fails and calling `m` gives the error

```
PiecewiseInterlace(Weighted(ChebyshevU() affine mapped to -2.8575156132357553..-2.3320423560125243), Weighted(ChebyshevU() affine mapped to 2.3954721587607026..2.8102753846598674)) * [1.245561077872868, 1.4916241471690674, -0.30295665832802066, 0.24711528604872615, 0.023421324704557652, 0.013448626954244836, -0.0007142380890863485, 0.0002966368362510001, 7.472913211842559e-6, 2.2905986564527903e-6  …  Error showing value of type QuasiArrays.ApplyQuasiVector{Float64, typeof(*), Tuple{PiecewiseInterlace{Float64, Tuple{Weighted{Float64, QuasiArrays.SubQuasiArray{Float64, 2, ChebyshevU{Float64}, Tuple{ContinuumArrays.AffineMap{Float64, Inclusion{Float64, IntervalSets.ClosedInterval{Float64}}, Inclusion{Float64, ChebyshevInterval{Float64}}}, Base.Slice{InfiniteArrays.OneToInf{Int64}}}, false}}, Weighted{Float64, QuasiArrays.SubQuasiArray{Float64, 2, ChebyshevU{Float64}, Tuple{ContinuumArrays.AffineMap{Float64, Inclusion{Float64, IntervalSets.ClosedInterval{Float64}}, Inclusion{Float64, ChebyshevInterval{Float64}}}, Base.Slice{InfiniteArrays.OneToInf{Int64}}}, false}}}}, BlockArrays.PseudoBlockVector{Float64, LazyArrays.ApplyArray{Float64, 1, typeof(vcat), Tuple{Vector{Float64}, FillArrays.Zeros{Float64, 1, Tuple{InfiniteArrays.OneToInf{Int64}}}}}, Tuple{BlockArrays.BlockedUnitRange{InfiniteArrays.InfStepRange{Int64, Int64}}}}}}:
ERROR: MethodError: no method matching isassigned(::BlockArrays.PseudoBlockVector{Float64, LazyArrays.ApplyArray{Float64, 1, typeof(vcat), Tuple{Vector{Float64}, FillArrays.Zeros{Float64, 1, Tuple{InfiniteArrays.OneToInf{Int64}}}}}, Tuple{BlockArrays.BlockedUnitRange{InfiniteArrays.InfStepRange{Int64, Int64}}}}, ::Infinities.RealInfinity)
Closest candidates are:
  isassigned(::AbstractArray, ::Integer...) at abstractarray.jl:511
```

**Comment by dlfivefifty** [comment]
Oh I said that because I didn't actually try it 😅 So it works by coincidence, awesome!

That `isassigned` bug should be fixed here https://github.com/JuliaArrays/InfiniteArrays.jl/pull/84 though it probably won't fix `plot`. I'll look into that.

**Comment by ioannisPApapadopoulos** [comment]
I am getting a package version requirements error that is a little tricky to resove when trying to add the `InfiniteArrays` branch `dl/realinfgetindex`

```
ERROR: Unsatisfiable requirements detected for package ContinuumArrays [7ae1f121]:
 ContinuumArrays [7ae1f121] log:
 ├─possible versions are: 0.0.1-0.9.1 or uninstalled
 ├─restricted to versions 0.9 by EquilibriumMeasures [f387465c], leaving only versions 0.9.0-0.9.1
 │ └─EquilibriumMeasures [f387465c] log:
 │   ├─possible versions are: 0.0.1 or uninstalled
 │   └─EquilibriumMeasures [f387465c] is fixed to version 0.0.1
 ├─restricted to versions 0.9.1-0.9 by ClassicalOrthogonalPolynomials [b30e2e7b], leaving only versions 0.9.1
 │ └─ClassicalOrthogonalPolynomials [b30e2e7b] log:
 │   ├─possible versions are: 0.4.7 or uninstalled
 │   ├─restricted to versions 0.4.7-0.4 by EquilibriumMeasures [f387465c], leaving only versions 0.4.7
 │   │ └─EquilibriumMeasures [f387465c] log: see above
 │   └─ClassicalOrthogonalPolynomials [b30e2e7b] is fixed to version 0.4.7
 └─restricted by compatibility requirements with InfiniteArrays [4858937d] to versions: 0.0.1-0.2.4 or uninstalled — no versions left
   └─InfiniteArrays [4858937d] log:
     ├─possible versions are: 0.12.0 or uninstalled
     └─InfiniteArrays [4858937d] is fixed to version 0.12.0
```

**Comment by dlfivefifty** [comment]
Just tagging ContinuumArrays.jl v0.9.2 now

**Comment by dlfivefifty** [comment]
Also pushed a fix for plotting to ClassicalOrthogonalPolynomials.jl

**Comment by ioannisPApapadopoulos** [comment]
Brilliant, thanks! The plotting now works on my end too!

**Comment by dlfivefifty** [comment]
@ioannisPApapadopoulos this is now working on tagged branches and has been merged 🎉

**Pull request merged**
